#!/bin/sh
# Generates a header file containing byte array of the contents of the input file
# ./biem test.txt -> text.txt.h

i=$1   # input file
o=$1.h # output file

var=$(basename $i | tr '.' '_')

echo "#pragma once" > $o
echo "const unsigned char $var[] = {" >> $o

# Writes the file as sequence of numbers, seperated correctly using commas
od $i -An -v -tu1 -w20 | sed -e 's/^ *//' -e 's/ \+/, /g' -e 's/$/,/g'>> $o

echo -e "};\n" >> $o

