#!/bin/sh
# Generates a header file containing byte array of the contents of the input file
# ./biem test.txt -> text.txt.h
i=$1
o=$1.h

guard=$(basename $i | tr '[a-z].' '[A-Z]_')
var=$(basename $i | tr '.' '_')

echo "#ifndef $guard"        >  $o
echo "#define $guard"        >> $o
echo "const char $var[] = {" >> $o

od $i -An -v -tu1 -w999999999 | sed -e 's/^ *//' -e 's/ \+/, /g' >> $o

echo "};"     >> $o
echo "#endif" >> $o

